- name: Run Shell Script on MyHosts Group
  hosts: master
  tasks:
    - name: Copy the script to remote servers
      copy:
        src: master.sh  # This is the local file on your machine
        dest: /home/ubuntu/master.sh  # This is where it will be on the remote server
        mode: '0755'  # Ensures it is executable

    - name: Execute the script on remote servers
      command: /home/ubuntu/master.sh