- name: Setup Kubernetes Cluster
  hosts: master
  tasks:
    - name: Copy master node script to master
      copy:
        src: master.sh
        dest: scripts/master.sh
        mode: '0755'

    - name: Run master node script
      shell: scripts/master.sh

    - name: Fetch worker join command
      shell: cat /home/ubuntu/worker-join-cmd
      register: join_command

    - name: Store complete join command
      set_fact:
        full_join_command: "{{ join_command.stdout | replace('\\\n', '') | replace('\t', ' ') | regex_replace(' +', ' ') | trim }}"

    - name: "Add shared var to dummy host"
      add_host:
        name:   "dummy-host"
        shared:   "{{ full_join_command }}"



- name: Setup Kubernetes Worker Nodes
  hosts: worker
  tasks:
    - name: Copy worker node script to worker
      copy:
        src: worker.sh
        dest: scripts/worker.sh
        mode: '0755'

    # For removing the error on --check
    - name: Check if worker.sh exists
      stat:
        path: scripts/worker.sh
      register: worker_script

    - name: Inject join command into worker script
      replace:
        path: scripts/worker.sh
        regexp: '#JOIN CMD COMES HERE'
        replace: "sudo {{ hostvars['dummy-host']['shared'] }}"
      when: worker_script.stat.exists

    - name: Run worker node script
      shell: scripts/worker.sh
