name: GitHub Actions Demo
run-name: K8s-Deploy

on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'A greeting'
        required: false
        default: 'Nope :('

      awsAccessKey:
        description: 'AWS Access Key'
        required: true

      awsSecretAccessKey:
        description: 'AWS Secret Access Key'
        required: true

      aws_region:
        description: 'AWS region to deploy resources'
        required: false
        default: 'us-east-1'

      ec2_count:
        description: 'Number of worker EC2 instances to create'
        required: false
        default: '3'

      ami_id:
        description: 'AMI ID for the EC2 instances'
        required: false
        default: 'ami-04b4f1a9cf54c11d0'

      instance_type:
        description: 'Instance type for the EC2 instances'
        required: false
        default: 't3.micro'

jobs:
  Provision:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository to access scripts, Terraform, and Ansible files
      - name: Checkout code
        uses: actions/checkout@v3

      # Generate RSA SSH Key
      - name: Generate RSA SSH Key
        run: |
          ssh-keygen -t rsa -b 4096 -m PEM -f ssh-key.pem -N ""
          cat ssh-key.pem
          cat ssh-key.pem > ansible-files/ssh-key.pem
          cat ssh-key.pem.pub > ssh-key_pub.pem
        id: ssh

      # Make scripts executable
      - name: Make Scripts Executable
        run: chmod +x ./scripts/*.sh

      # Install Terraform
      - name: Install Terraform
        run: ./scripts/install-terraform.sh

      # Initialize and Apply Terraform
      - name: Terraform Init and Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.awsAccessKey }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.awsSecretAccessKey }}
        run: |
          cd terraform-files
          terraform init
          terraform apply -auto-approve \
            -var="aws_region=${{ github.event.inputs.aws_region }}" \
            -var="ec2_count=${{ github.event.inputs.ec2_count }}" \
            -var="ami_id=${{ github.event.inputs.ami_id }}" \
            -var="instance_type=${{ github.event.inputs.instance_type }}" \
            -var="ssh_public_key=$(cat ../ssh-key_pub.pem)" \
            -var="s3_object_source=../ssh-key.pem"
        
          # Capture the output IPs
          terraform output -json public_ips > ../ansible-files/ips.json
          cat ../ansible-files/ips.json

      # Prepare Ansible Inventory File
      - name: Generate Ansible Inventory
        run: |
          jq -r '
            to_entries[] |
            if .key == 0 then "[master]\n" + .value + "\n\n[worker]"
            else .value
            end
          ' ansible-files/ips.json > ansible-files/inventory.ini

          # Append Ansible vars to the inventory
          echo "[all:vars]" >> ansible-files/inventory.ini
          echo "ansible_user=ubuntu" >> ansible-files/inventory.ini
          echo "ansible_ssh_private_key_file=ssh-key.pem" >> ansible-files/inventory.ini
          
          cat ansible-files/inventory.ini

      # Run Ansible Playbook
      - name: Run Ansible Playbook
        run: |
          cd ansible-files
          cat  ssh-key.pem
          chmod 600 ssh-key.pem
          ansible-playbook -i inventory.ini playbook.yml

      # Greetings Step
      - name: Greetings!
        run: echo "${{ github.event.inputs.greeting }}"
