name: GitHub Actions Demo
run-name: K8s-Deploy

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: "User's Name"
        required: true

      awsAccessKey:
        description: 'AWS Access Key'
        required: true

      awsSecretAccessKey:
        description: 'AWS Secret Access Key'
        required: true

      aws_region:
        description: 'AWS region to deploy resources'
        required: false
        default: 'us-east-1'

      ec2_count:
        description: 'Number of worker EC2 instances to create'
        required: false
        default: '3'

      ami_id:
        description: 'AMI ID for the EC2 instances'
        required: false
        default: 'ami-04b4f1a9cf54c11d0'

      instance_type:
        description: 'Instance type for the EC2 instances'
        required: false
        default: 't3.micro'

jobs:
  Provision:
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.inputs.user_name }}
        uses: actions/checkout@v3

      # Checkout the repository to access scripts, Terraform, and Ansible files
      - name: Checkout code
        uses: actions/checkout@v3

      # Generate RSA SSH Key
      - name: Generate RSA SSH Key
        run: |
          ssh-keygen -t rsa -b 4096 -m PEM -f ssh-key.pem -N ""
          mkdir ~/.ssh
          cat ssh-key.pem > ~/.ssh/id_rsa
          cat ssh-key.pem.pub > ssh-key_pub.pem
        id: ssh

      # Make scripts executable
      - name: Make Scripts Executable
        run: chmod +x ./scripts/*.sh

      # Install Terraform
      - name: Install Terraform
        run: ./scripts/install-terraform.sh

      # Initialize and Apply Terraform
      - name: Terraform Init and Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.awsAccessKey }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.awsSecretAccessKey }}
        run: |
          cd terraform-files
          terraform init
          terraform apply -auto-approve \
            -var="aws_region=${{ github.event.inputs.aws_region }}" \
            -var="ec2_count=${{ github.event.inputs.ec2_count }}" \
            -var="ami_id=${{ github.event.inputs.ami_id }}" \
            -var="instance_type=${{ github.event.inputs.instance_type }}" \
            -var="ssh_public_key=$(cat ../ssh-key_pub.pem)" \
            -var="s3_object_source=../ssh-key.pem"
        
          # Capture the output IPs
          terraform output -json public_ips > ../ansible-files/ips.json
          cat ../ansible-files/ips.json

      # Prepare Ansible Inventory File
      - name: Generate Ansible Inventory
        run: |
          jq -r '
            to_entries[] |
            if .key == 0 then "[master]\n" + .value + "\n\n[worker]"
            else .value
            end
          ' ansible-files/ips.json > ansible-files/inventory.ini

          # Append Ansible vars to the inventory
          echo "[all:vars]" >> ansible-files/inventory.ini
          echo "ansible_user=ubuntu" >> ansible-files/inventory.ini
          echo "ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible-files/inventory.ini
          
          cat ansible-files/inventory.ini

      # Disable Strict Host Key Checking To Stop It From Prompting During SSH
      - name: Disable Strict Host Key Checking
        run: echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      # Add all IP addresses to known_hosts
      - name: Add IPs to known_hosts
        run: |
          cd ansible-files
          IP_LIST=$(jq -r '.[]' ips.json)
          for ip in $IP_LIST; do
            echo "Adding $ip to known_hosts"
            ssh-keyscan -H $ip >> ~/.ssh/known_hosts || true
          done
          cat ~/.ssh/known_hosts

      # Ping Instances and Retry if Failed
      - name: Ping Instances (Retry if Failed)
        run: |
          cd ansible-files
          retries=3
          count=0
          success=false
          while [ $count -lt $retries ]; do
            echo "Attempt $((count + 1)) to ping the instances..."
            ansible all -i inventory.ini -m ping
            if [ $? -eq 0 ]; then
              success=true
              break
            fi
            echo "Ping failed, retrying in 10 seconds..."
            sleep 10
            count=$((count + 1))
          done

          if [ "$success" = false ]; then
            echo "Ping failed after 3 attempts. Aborting deployment."
            exit 1
          fi

      # Run Ansible Playbook
      - name: Run Ansible Playbook
        if: success == 'true'
        run: |
          cd ansible-files
          sudo chmod 600 ~/.ssh/id_rsa
          ansible-playbook -i inventory.ini playbook.yml -vv
