name: GitHub Actions Demo
run-name: K8s-Deploy
on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'A greeting'
        required: false
        default: 'Nope :('
      awsAccessKey:
        description: 'AWS Access Key'
        required: true
      awsSecretAccessKey:
        description: 'AWS Secret Access Key'
        required: true

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository to access scripts and Terraform files
      - name: Checkout code
        uses: actions/checkout@v3

      # Generate RSA SSH Key
      - name: Generate RSA SSH Key
        run: |
          ssh-keygen -t rsa -b 4096 -m PEM -f ssh-key.pem -N ""
          ssh-keygen -f ssh-key.pem -e -m PEM > ssh-key_pub.pem

      # Make the install script executable
      - name: Make Install Script Executable
        run: chmod +x ./scripts/install-terraform.sh

      # Install Terraform using the provided script
      - name: Install Terraform
        run: ./scripts/install-terraform.sh

      # Initialize and Apply Terraform configuration with AWS credentials set
      - name: Terraform Init and Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.awsAccessKey }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.awsSecretAccessKey }}
        run: |
          echo "AWS credentials starts with ${AWS_ACCESS_KEY_ID:0:4}"
          cd terraform-files
          terraform init
          terraform apply -auto-approve

      # Greetings Step
      - name: Greetings!
        run: echo "${{ github.event.inputs.greeting }}"
